core/urls.py
from django.urls import include, path


from . import views as cores_views

urlpatterns = [
    path('', cores_views.IndexListView.as_view(), name='index'),
]

plataforma/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('accounts.urls')),
    path('', include('ticker.urls')),
]



urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

core/models.py
from uuid import uuid4

from django.db import models
from django.utils.translation import ugettext_lazy as _

class BaseModelField(models.Model):
    """Classe de composição para modelos que utilizaram os
        campos created_at, updated_at
    """
    code = models.UUIDField(
        primary_key=True,
        default=uuid4,
        editable=False
    )

    is_active = models.BooleanField(default=True)

    created_at = models.DateTimeField(
        _('Criado em'), auto_now_add=True,
        db_column='created_at'
    )
    updated_at = models.DateTimeField(
        _('Aualizado em'), auto_now=True,
        db_column='updated_at'
    )

    class Meta:
        abstract = True


class UserVsTicker(BaseModelField):

    user = models.OneToOneField(
        'accounts.User', related_name='user_vs_ticker_related',
        verbose_name=_('Usuário'), on_delete=models.CASCADE
    )

    ticker = models.ManyToManyField(
        'ticker.Ticker', verbose_name=_('Ticker'),
        related_name='user_vs_ticker_related'
    )

    def __str__(self):
        return f'{self.user.name} - Ticker: {self.ticker.count()}'

core/forms.py
from utils.validation import isfloat
from decimal import Decimal
import json
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth import get_user_model

from django import forms
from core.models import UserVsTicker
from apis.api_rapidapi_brapi import get_ticker
from ticker.models import Ticker
User = get_user_model()


class UserVsTickerForm(forms.Form):
    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)

        self.fields['user'].widget = forms.HiddenInput()
        self.fields['ticker'].widget.attrs['list'] = 'datalistOptions'
        if user:
            self.fields['user'].initial = user

    ticker = forms.CharField(label='Empresa', max_length=300)

    user = forms.ModelChoiceField(label='Cliente', queryset=User.objects.all())

    class Meta:
        fields = ['user', 'ticker']

    def clean_user(self):
        user = self.cleaned_data.get('user')
        if not user:
            raise forms.ValidationError('Usuário não existe')

        return user

    def clean_ticker(self):
        ticker = self.cleaned_data.get('ticker')
        response = get_ticker(ticker)
        if response.status_code != 200:
            tk = Ticker.objects.filter(ticker=ticker)
            if not tk.exists():
                raise forms.ValidationError(
                    f"CODE: {response.status_code}: Ticker {ticker.upper()}, não Encontrado")
            return tk[0]

        ticker = ticker.upper()
        json_data = json.loads((response.text).replace(
            'yield', 'media'))

        ticker_data = {}

        for k, v in json_data.items():
            if hasattr(Ticker, k.lower()) or v:
                if ',' in v and isfloat(v):
                    v = Decimal(v.replace(',', '.'))

                ticker_data[k.lower()] = v

        ticker = Ticker.objects.update_or_create(
            ticker=ticker,
            defaults=ticker_data
        )[0]

        return ticker

    def save(self):
        user = self.cleaned_data.get('user')
        tk = self.cleaned_data.get('ticker')
        uvt = UserVsTicker.objects.get(user=user.pk)
        uvt.ticker.add(tk)

        return uvt

core/views.py
from django.utils import timezone
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import TemplateView, CreateView, DeleteView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from core.models import UserVsTicker
from ticker.tasks import task_ticker_update_all
from ticker.tasks import task_list_ticker,get_ticker

class IndexListView(LoginRequiredMixin, ListView):
    template_name = 'core/index.html'
    login_url = reverse_lazy('login')
    model = UserVsTicker
    context_object_name = 'objects'

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs).filter(user=self.request.user)
        task_ticker_update_all(qs.values_list('ticker__ticker',flat=True))
        return qs

    def get_context_data(self, **kwargs):
        if self.request.user.is_superuser:
            task_list_ticker()
        

        context = super().get_context_data(**kwargs)
        context['now'] = timezone.now()
        return context

    def get(self, request, *args, **kwargs):

        return super().get(request, *args, **kwargs)

core/templates/core/partial/_btn.html
{% load static bootstrap5 custom_filters %}

<div class="row row-cols-1 row-cols-md-2 p-4 text-uppercase">
    <form action="{% url 'ticker_update' %}" method="post">
        {% csrf_token %}
        <div id='search-input-add' class="w-100 mb-2">
            <input type="text" name='ticker' id='id_ticker' class="form-control bg-light border-1 small"
                placeholder="Buscar..." aria-label="Search" aria-describedby="basic-addon2" required>
            <ul class='autocomplete-result-list'
                style='background-color: #FFFFFF; padding-top:20px;padding-bottom: 20px; border-radius: 0 0 15px 15px; position: relative; z-index: 9999'
                id="autocomplete-result-list-menu">
            </ul>
            <input type="text" name="user" id="id_user" value="{{ request.user.pk }}" hidden="true">

        </div>
        <button type="submit" class="btn btn-success w-100 mb-4 text-uppercase">Adicionar</button>

    </form>
    <form action="{% url 'ticker_delete' %}" method="post">
        {% csrf_token %}
        <div id='search-input-del' class="w-100 mb-2">
            <input type="text" name='ticker' id='id_ticker' class="form-control bg-light border-1 small"
                placeholder="Buscar..." aria-label="Search" aria-describedby="basic-addon2" required>
            <ul class='autocomplete-result-list'
                style='background-color: #FFFFFF; padding-top:20px;padding-bottom: 20px; border-radius: 0 0 15px 15px; position: relative; z-index: 9999'
                id="autocomplete-result-list-menu">
            </ul>
            <input type="text" name="user" id="id_user" value="{{ request.user.pk }}" hidden="true">

        </div>

        <button type="submit" class="btn btn-danger w-100 mb-4 text-uppercase">Remover</button>

    </form>

</div>

core/templates/core/partial/_cards.html
{% load static bootstrap5 custom_filters %}

<div class="row row-cols-1 row-cols-md-2">
    {% for obj in object_list %}

    {% for tk in obj.ticker.all %}
    <div class="col mb-3">
        <div class="card ticker" data-url="{% url 'ticker_data' tk.pk %}">
            <div class="card-body">
                <div class="row row-cols-2 align-items-center">
                    <img src="{{tk.logo}}" alt="{{tk.name}}" class="img-fluid">
                    <div class="ticker d-relative">
                        <h5>{{tk.ticker}}</h5>
                        <div class="i fa-solid fa-check text-success fa-3x d-none"></div>
                    </div>
                </div>
            </div>
            <div class="card-footer">
                <div class="row row-cols-2 align-items-center">
                    <strong class="text-{% if tk.close > tk.media %}success{% else%}danger{% endif %}">
                        {{tk.close|money}} <i
                            class="fa-solid fa-arrow-{% if tk.close > tk.media %}up{% else %}down{% endif %}"></i>
                        <span class="text-muted">~{{tk.media}}</span>

                    </strong>
                    <div clas="d-flex flex-direction-column">
                        <div class="">
                            <span class="text-muted">
                                Min:
                                <strong>{{tk.min}}</strong>
                            </span>
                        </div>
                        <div class="">
                            <span class="text-muted">
                                Max:
                                <strong>{{tk.max}}</strong>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
    {% endfor %}
    {% endfor %}
</div>